# Configuration: https://dependabot.com/docs/config-file/
# Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically


version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "poetry" # If you want to manage Poetry updates manually, you can specify here

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
      - match:
          dependency-name: "poetry"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50
