name: CLI Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11.x'

env:
  RUNTIME__LOG_LEVEL: ERROR
  ENV: 'dev'

jobs:
  cli-unit-tests:
    name: CLI Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run CLI Unit Tests
        run: uv run pytest cognee/tests/unit/cli/ -v

  cli-integration-tests:
    name: CLI Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run CLI Integration Tests
        run: uv run pytest cognee/tests/integration/cli/ -v

  cli-functionality-tests:
    name: CLI Functionality Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: ${{ inputs.python-version }}

      - name: Test CLI Help Commands
        run: |
          uv run python -m cognee.cli._cognee --help
          uv run python -m cognee.cli._cognee --version
          uv run python -m cognee.cli._cognee add --help
          uv run python -m cognee.cli._cognee search --help
          uv run python -m cognee.cli._cognee cognify --help
          uv run python -m cognee.cli._cognee delete --help
          uv run python -m cognee.cli._cognee config --help

      - name: Test CLI Config Subcommands
        run: |
          uv run python -m cognee.cli._cognee config get --help
          uv run python -m cognee.cli._cognee config set --help
          uv run python -m cognee.cli._cognee config list --help
          uv run python -m cognee.cli._cognee config unset --help
          uv run python -m cognee.cli._cognee config reset --help

      - name: Test CLI Error Handling
        run: |
          # Test invalid command (should fail gracefully)
          ! uv run python -m cognee.cli._cognee invalid_command
          
          # Test missing required arguments (should fail gracefully)
          ! uv run python -m cognee.cli._cognee search
          
          # Test invalid search type (should fail gracefully)
          ! uv run python -m cognee.cli._cognee search "test" --query-type INVALID_TYPE
          
          # Test invalid chunker (should fail gracefully)
          ! uv run python -m cognee.cli._cognee cognify --chunker InvalidChunker
